version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass someredispassword
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./expensy_backend
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8706:8706"
    environment:
      PORT: 8706
      DATABASE_URI: mongodb://root:example@mongo:27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: someredispassword
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./expensy_frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8706
    depends_on:
      - backend