apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
type: Opaque
stringData:
  DATABASE_URI: {{ .Values.secrets.databaseUri }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword }}
  MONGO_ROOT_USERNAME: {{ .Values.secrets.mongoRootUsername }}
  MONGO_ROOT_PASSWORD: {{ .Values.secrets.mongoRootPassword }}
