apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: devops-final-project-ih-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8706
          env:
            - name: PORT
              value: "8706"
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: expensy-secrets
                  key: DATABASE_URI
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expensy-secrets
                  key: REDIS_PASSWORD
