apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
type: Opaque
stringData:
  DATABASE_URI: REPLACE_WITH_YOUR_DATABASE_URI
  REDIS_PASSWORD: REPLACE_WITH_YOUR_REDIS_PASSWORD
  MONGO_ROOT_USERNAME: REPLACE_WITH_YOUR_MONGO_USERNAME
  MONGO_ROOT_PASSWORD: REPLACE_WITH_YOUR_MONGO_PASSWORD
